### ISSUE TITLE
Ubuntu 16.04 LTS Xenial support

### ISSUE THREAD

**Issue by pabloab** [yktoo/indicator-docker#1]
Seems [you build this package](https://launchpad.net/~yktooo/+archive/ubuntu/ppa/+packages) for latest versions of Ubuntu but not the last LTS, 16.04.

**Comment by yktoo** [comment]
Copied to the Xenial series.

**Comment by pabloab** [comment]
```
pablo ~ $ indicator-docker -vv 
Traceback (most recent call last):
  File "/usr/bin/indicator-docker", line 28, in <module>
    import docker
ImportError: No module named 'docker'
pablo ~ $ python --version
Python 2.7.12

```

**Comment by yktoo** [comment]
You need to fulfil the requirements and install the `docker` module for Python3. Xenial had Python 2 as the default, so in order to install it you need to run `sudo pip3 install docker`. I'll update the README.

**Comment by pabloab** [comment]
Would be great the package install all it dependencies.
Well, I didn't have so I `sudo apt install python3-pip` (which installed `libpython3-dev libpython3.5-dev python3-dev python3-setuptools python3-wheel python3.5-dev`) then finally `pip3 install docker`. Now still doesn't run, [here the logs](https://github.com/yktoo/indicator-docker/files/1117125/indicator-docker-output_xenial.txt), some "Permission denied", don't sure why...

**Comment by yktoo** [comment]
I agree with you, but like I said the Python Docker lib's version in the official repository is outdated, and the only way to provide it would be to package it myself. Maybe it's something for the future.

As for the logs, this permission denied error is new to me, I guess it might be some Docker API issue. Can you start `python3` and type in the following commands to see if anything fails:
```python
>>> import docker
>>> a = docker.from_env()
>>> a.info()
```

**Comment by pabloab** [comment]
Sorry to hear that, seems we would need to wait to have this indicator on last LTS Ubuntu.
[Attached TXT](https://github.com/yktoo/indicator-docker/files/1119665/python3_docker_info_output.txt) with the output of those commands on Python console. Again the permission issue.

**Comment by yktoo** [comment]
It's clearly something related to Docker and/or your machine setup. Are you otherwise able to perform container operations with your user? Is your user a member of `docker` group?
