### ISSUE TITLE
Namespace AppIndicator3 not available

### ISSUE THREAD

**Issue by medamines1** [yktoo/indicator-docker#5]
when running the indicator I get this trace

Traceback (most recent call last):
  File "/usr/local/bin/indicator-docker", line 39, in <module>
    require_version('AppIndicator3', '0.1')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 130, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace AppIndicator3 not available

**Comment by yktoo** [comment]
Do you have `gir1.2-appindicator3-0.1` or `gir1.2-ayatanaappindicator3-0.1` installed?

**Comment by medamines1** [comment]
well I checked pip freeze and they are not installed

**Comment by yktoo** [comment]
These are Debian (not pip) packages, you may try to run:
```bash
sudo apt install gir1.2-appindicator3-0.1
```

**Comment by medamines1** [comment]
ValueError: Namespace Notify not available
and guake (terminal app) stoped working i think it's related

**Comment by yktoo** [comment]
Could you provide the entire stack trace?

**Comment by medamines1** [comment]
ok I was able to fix the problems and the indicator runs without showing errors but nothing appears any ideas? thanks for responding.

**Comment by yktoo** [comment]
If by nothing you mean you don't see an icon, then it either your desktop environment fails to find the icon file, or a problem with the indicator support library.

Do you get the menu with an missing (empty) icon, or no menu at all?

**Comment by medamines1** [comment]
No menu at all.

**Comment by LeonMelis** [comment]
I ran into the same problem after installing version 2.3.4-1 through dpkg.

I fixed this with:

```
sudo apt --fix-broken install
```
